@startuml
class Reactor{
    - unique_ptr<Epoller> ptr_epoller
    - int epoll_fd_
    + void register_handler(Handler* ptr_handler)
    + void remove_handler(Handler* ptr_handler)
    + void loop()
}
@enduml