@startuml
Server -> Acceptor: start_server()
Acceptor -> Acceptor: server_bind()
Acceptor -> Acceptor: server_listen()
Server -> Handler: Create new Handler object ptr_handler with server fd
Handler -> Handler: setReadCallback as Server::accept
Handler -> Handler: enable_read()
Server -> Reactor: register_handler(ptr_handler)
@enduml